orbs:
  aws-cli: circleci/aws-cli@4.0.0
version: 2.1
executors:
  app-executor:
    docker:
      - image: cimg/node:20.5.1
      - image: cimg/base:2023.08
    working_directory: ~/repo
  terraform-executor:
    docker:
      - image: hashicorp/terraform:latest
      - image: cimg/base:2023.08

aliases:
  - &show-current-branch-name
    run:
      name: Show current branch name
      command: echo "Current branch name is $CIRCLE_BRANCH"
  - &restore-cache
    restore_cache:
      keys:
        - app-{{ checksum "package.json" }}
        - app-
  - &install-dependencies
    run:
      name: Install dependencies
      command: pnpm install --no-frozen-lockfile
  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{{ checksum "package.json" }}

jobs:
  install-dependencies:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - *install-dependencies
      - *save-cache

workflows:
  build_and_deploy:
    jobs:
      - install-dependencies